server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://172.16.218.158:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: test_route
        uri: lb://test
        predicates:
          - Path=/test/**
      - id: test1_route
        uri: lb://test1
        predicates:
          - Path=/test1/**

      default-filters:
        - StripPrefix=1


