package top.fqq.mybatisgenerator.dao;

import top.fqq.mybatisgenerator.model.alarmLog;

public interface alarmLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cos_alarm_log
     *
     * @mbggenerated Wed Apr 14 10:19:46 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cos_alarm_log
     *
     * @mbggenerated Wed Apr 14 10:19:46 CST 2021
     */
    int insert(alarmLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cos_alarm_log
     *
     * @mbggenerated Wed Apr 14 10:19:46 CST 2021
     */
    int insertSelective(alarmLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cos_alarm_log
     *
     * @mbggenerated Wed Apr 14 10:19:46 CST 2021
     */
    alarmLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cos_alarm_log
     *
     * @mbggenerated Wed Apr 14 10:19:46 CST 2021
     */
    int updateByPrimaryKeySelective(alarmLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cos_alarm_log
     *
     * @mbggenerated Wed Apr 14 10:19:46 CST 2021
     */
    int updateByPrimaryKey(alarmLog record);
}