package top.fqq.mybatisgenerator.model;

import java.util.Date;

public class alarmLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.id
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.first_id
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private String firstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.alarm_code
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private String alarmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.alarm_name
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private String alarmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.alarm_level
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private Short alarmLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.alarm_data
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private String alarmData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.occurrence_time
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private Date occurrenceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.cleared_time
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private Date clearedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.cleared_user
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private String clearedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cos_alarm_log.additional_info
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    private String additionalInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.id
     *
     * @return the value of t_cos_alarm_log.id
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.id
     *
     * @param id the value for t_cos_alarm_log.id
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.first_id
     *
     * @return the value of t_cos_alarm_log.first_id
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public String getFirstId() {
        return firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.first_id
     *
     * @param firstId the value for t_cos_alarm_log.first_id
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setFirstId(String firstId) {
        this.firstId = firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.alarm_code
     *
     * @return the value of t_cos_alarm_log.alarm_code
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public String getAlarmCode() {
        return alarmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.alarm_code
     *
     * @param alarmCode the value for t_cos_alarm_log.alarm_code
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setAlarmCode(String alarmCode) {
        this.alarmCode = alarmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.alarm_name
     *
     * @return the value of t_cos_alarm_log.alarm_name
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public String getAlarmName() {
        return alarmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.alarm_name
     *
     * @param alarmName the value for t_cos_alarm_log.alarm_name
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.alarm_level
     *
     * @return the value of t_cos_alarm_log.alarm_level
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public Short getAlarmLevel() {
        return alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.alarm_level
     *
     * @param alarmLevel the value for t_cos_alarm_log.alarm_level
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setAlarmLevel(Short alarmLevel) {
        this.alarmLevel = alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.alarm_data
     *
     * @return the value of t_cos_alarm_log.alarm_data
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public String getAlarmData() {
        return alarmData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.alarm_data
     *
     * @param alarmData the value for t_cos_alarm_log.alarm_data
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setAlarmData(String alarmData) {
        this.alarmData = alarmData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.occurrence_time
     *
     * @return the value of t_cos_alarm_log.occurrence_time
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public Date getOccurrenceTime() {
        return occurrenceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.occurrence_time
     *
     * @param occurrenceTime the value for t_cos_alarm_log.occurrence_time
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setOccurrenceTime(Date occurrenceTime) {
        this.occurrenceTime = occurrenceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.cleared_time
     *
     * @return the value of t_cos_alarm_log.cleared_time
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public Date getClearedTime() {
        return clearedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.cleared_time
     *
     * @param clearedTime the value for t_cos_alarm_log.cleared_time
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setClearedTime(Date clearedTime) {
        this.clearedTime = clearedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.cleared_user
     *
     * @return the value of t_cos_alarm_log.cleared_user
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public String getClearedUser() {
        return clearedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.cleared_user
     *
     * @param clearedUser the value for t_cos_alarm_log.cleared_user
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setClearedUser(String clearedUser) {
        this.clearedUser = clearedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cos_alarm_log.additional_info
     *
     * @return the value of t_cos_alarm_log.additional_info
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cos_alarm_log.additional_info
     *
     * @param additionalInfo the value for t_cos_alarm_log.additional_info
     *
     * @mbggenerated Wed Apr 14 10:59:00 CST 2021
     */
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
}